<?xml version="1.0" encoding="utf-8"?><Database Name="QB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.AnhDiaDiem" Member="AnhDiaDiems">
    <Type Name="AnhDiaDiem">
      <Column Name="MaAnh" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDiaDiem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DuongDanAnh" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LaAnhChinh" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DiaDiem_AnhDiaDiem" Member="DiaDiem" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="DiaDiem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TraiNghiem" Member="TraiNghiems">
    <Type Name="TraiNghiem">
      <Column Name="MaTraiNghiem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDiaDiem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoaiTraiNghiem" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TieuDe" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Icon" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="DiaDiem_TraiNghiem" Member="DiaDiem" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="DiaDiem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="MaDanhMuc" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="DanhMuc_DiaDiem" Member="DiaDiems" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="DiaDiem" />
    </Type>
  </Table>
  <Table Name="dbo.DiaDiem" Member="DiaDiems">
    <Type Name="DiaDiem">
      <Column Name="MaDiaDiem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDiaDiem" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Slug" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MoTaNgan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MoTaChiTiet" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaDanhMuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GiaVe" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GioMoCua" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="VungMien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KinhDo" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="ViDo" Type="System.Decimal" DbType="Decimal(18,10)" CanBeNull="true" />
      <Column Name="DiaChiChiTiet" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LuotXem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DiemDanhGiaTB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="NgayDang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DiaDiem_AnhDiaDiem" Member="AnhDiaDiems" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="AnhDiaDiem" />
      <Association Name="DiaDiem_TraiNghiem" Member="TraiNghiems" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="TraiNghiem" />
      <Association Name="DiaDiem_GiaVeChiTiet" Member="GiaVeChiTiets" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="GiaVeChiTiet" />
      <Association Name="DanhMuc_DiaDiem" Member="DanhMuc" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="DanhMuc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GiaVeChiTiet" Member="GiaVeChiTiets">
    <Type Name="GiaVeChiTiet">
      <Column Name="MaGiaVe" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaDiaDiem" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoaiKhach" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="DiaDiem_GiaVeChiTiet" Member="DiaDiem" ThisKey="MaDiaDiem" OtherKey="MaDiaDiem" Type="DiaDiem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NguoiDung" Member="NguoiDungs">
    <Type Name="NguoiDung">
      <Column Name="MaNguoiDung" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="MatKhauHash" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TieuSu" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ThanhPho" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QuocGia" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="AnhDaiDien" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VaiTro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="NgayCapNhat" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
</Database>