#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTW_CK_QuangBaVietNam.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnhDiaDiem(AnhDiaDiem instance);
    partial void UpdateAnhDiaDiem(AnhDiaDiem instance);
    partial void DeleteAnhDiaDiem(AnhDiaDiem instance);
    partial void InsertTraiNghiem(TraiNghiem instance);
    partial void UpdateTraiNghiem(TraiNghiem instance);
    partial void DeleteTraiNghiem(TraiNghiem instance);
    partial void InsertDanhMuc(DanhMuc instance);
    partial void UpdateDanhMuc(DanhMuc instance);
    partial void DeleteDanhMuc(DanhMuc instance);
    partial void InsertDiaDiem(DiaDiem instance);
    partial void UpdateDiaDiem(DiaDiem instance);
    partial void DeleteDiaDiem(DiaDiem instance);
    partial void InsertGiaVeChiTiet(GiaVeChiTiet instance);
    partial void UpdateGiaVeChiTiet(GiaVeChiTiet instance);
    partial void DeleteGiaVeChiTiet(GiaVeChiTiet instance);
    partial void InsertNguoiDung(NguoiDung instance);
    partial void UpdateNguoiDung(NguoiDung instance);
    partial void DeleteNguoiDung(NguoiDung instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AnhDiaDiem> AnhDiaDiems
		{
			get
			{
				return this.GetTable<AnhDiaDiem>();
			}
		}
		
		public System.Data.Linq.Table<TraiNghiem> TraiNghiems
		{
			get
			{
				return this.GetTable<TraiNghiem>();
			}
		}
		
		public System.Data.Linq.Table<DanhMuc> DanhMucs
		{
			get
			{
				return this.GetTable<DanhMuc>();
			}
		}
		
		public System.Data.Linq.Table<DiaDiem> DiaDiems
		{
			get
			{
				return this.GetTable<DiaDiem>();
			}
		}
		
		public System.Data.Linq.Table<GiaVeChiTiet> GiaVeChiTiets
		{
			get
			{
				return this.GetTable<GiaVeChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDung> NguoiDungs
		{
			get
			{
				return this.GetTable<NguoiDung>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AnhDiaDiem")]
	public partial class AnhDiaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaAnh;
		
		private int _MaDiaDiem;
		
		private string _DuongDanAnh;
		
		private System.Nullable<bool> _LaAnhChinh;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaAnhChanging(int value);
    partial void OnMaAnhChanged();
    partial void OnMaDiaDiemChanging(int value);
    partial void OnMaDiaDiemChanged();
    partial void OnDuongDanAnhChanging(string value);
    partial void OnDuongDanAnhChanged();
    partial void OnLaAnhChinhChanging(System.Nullable<bool> value);
    partial void OnLaAnhChinhChanged();
    #endregion
		
		public AnhDiaDiem()
		{
			this._DiaDiem = default(EntityRef<DiaDiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaAnh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaAnh
		{
			get
			{
				return this._MaAnh;
			}
			set
			{
				if ((this._MaAnh != value))
				{
					this.OnMaAnhChanging(value);
					this.SendPropertyChanging();
					this._MaAnh = value;
					this.SendPropertyChanged("MaAnh");
					this.OnMaAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="Int NOT NULL")]
		public int MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuongDanAnh", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string DuongDanAnh
		{
			get
			{
				return this._DuongDanAnh;
			}
			set
			{
				if ((this._DuongDanAnh != value))
				{
					this.OnDuongDanAnhChanging(value);
					this.SendPropertyChanging();
					this._DuongDanAnh = value;
					this.SendPropertyChanged("DuongDanAnh");
					this.OnDuongDanAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaAnhChinh", DbType="Bit")]
		public System.Nullable<bool> LaAnhChinh
		{
			get
			{
				return this._LaAnhChinh;
			}
			set
			{
				if ((this._LaAnhChinh != value))
				{
					this.OnLaAnhChinhChanging(value);
					this.SendPropertyChanging();
					this._LaAnhChinh = value;
					this.SendPropertyChanged("LaAnhChinh");
					this.OnLaAnhChinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_AnhDiaDiem", Storage="_DiaDiem", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.AnhDiaDiems.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.AnhDiaDiems.Add(this);
						this._MaDiaDiem = value.MaDiaDiem;
					}
					else
					{
						this._MaDiaDiem = default(int);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TraiNghiem")]
	public partial class TraiNghiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTraiNghiem;
		
		private int _MaDiaDiem;
		
		private string _LoaiTraiNghiem;
		
		private string _TieuDe;
		
		private string _MoTa;
		
		private string _Icon;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTraiNghiemChanging(int value);
    partial void OnMaTraiNghiemChanged();
    partial void OnMaDiaDiemChanging(int value);
    partial void OnMaDiaDiemChanged();
    partial void OnLoaiTraiNghiemChanging(string value);
    partial void OnLoaiTraiNghiemChanged();
    partial void OnTieuDeChanging(string value);
    partial void OnTieuDeChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnIconChanging(string value);
    partial void OnIconChanged();
    #endregion
		
		public TraiNghiem()
		{
			this._DiaDiem = default(EntityRef<DiaDiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTraiNghiem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTraiNghiem
		{
			get
			{
				return this._MaTraiNghiem;
			}
			set
			{
				if ((this._MaTraiNghiem != value))
				{
					this.OnMaTraiNghiemChanging(value);
					this.SendPropertyChanging();
					this._MaTraiNghiem = value;
					this.SendPropertyChanged("MaTraiNghiem");
					this.OnMaTraiNghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="Int NOT NULL")]
		public int MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTraiNghiem", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiTraiNghiem
		{
			get
			{
				return this._LoaiTraiNghiem;
			}
			set
			{
				if ((this._LoaiTraiNghiem != value))
				{
					this.OnLoaiTraiNghiemChanging(value);
					this.SendPropertyChanging();
					this._LoaiTraiNghiem = value;
					this.SendPropertyChanged("LoaiTraiNghiem");
					this.OnLoaiTraiNghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuDe", DbType="NVarChar(255)")]
		public string TieuDe
		{
			get
			{
				return this._TieuDe;
			}
			set
			{
				if ((this._TieuDe != value))
				{
					this.OnTieuDeChanging(value);
					this.SendPropertyChanging();
					this._TieuDe = value;
					this.SendPropertyChanged("TieuDe");
					this.OnTieuDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="VarChar(100)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this.OnIconChanging(value);
					this.SendPropertyChanging();
					this._Icon = value;
					this.SendPropertyChanged("Icon");
					this.OnIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TraiNghiem", Storage="_DiaDiem", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.TraiNghiems.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.TraiNghiems.Add(this);
						this._MaDiaDiem = value.MaDiaDiem;
					}
					else
					{
						this._MaDiaDiem = default(int);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMuc")]
	public partial class DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDanhMuc;
		
		private string _TenDanhMuc;
		
		private string _MoTa;
		
		private EntitySet<DiaDiem> _DiaDiems;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDanhMucChanging(int value);
    partial void OnMaDanhMucChanged();
    partial void OnTenDanhMucChanging(string value);
    partial void OnTenDanhMucChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public DanhMuc()
		{
			this._DiaDiems = new EntitySet<DiaDiem>(new Action<DiaDiem>(this.attach_DiaDiems), new Action<DiaDiem>(this.detach_DiaDiems));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanhMuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDanhMuc
		{
			get
			{
				return this._MaDanhMuc;
			}
			set
			{
				if ((this._MaDanhMuc != value))
				{
					this.OnMaDanhMucChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMuc = value;
					this.SendPropertyChanged("MaDanhMuc");
					this.OnMaDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDanhMuc", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDanhMuc
		{
			get
			{
				return this._TenDanhMuc;
			}
			set
			{
				if ((this._TenDanhMuc != value))
				{
					this.OnTenDanhMucChanging(value);
					this.SendPropertyChanging();
					this._TenDanhMuc = value;
					this.SendPropertyChanged("TenDanhMuc");
					this.OnTenDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_DiaDiem", Storage="_DiaDiems", ThisKey="MaDanhMuc", OtherKey="MaDanhMuc")]
		public EntitySet<DiaDiem> DiaDiems
		{
			get
			{
				return this._DiaDiems;
			}
			set
			{
				this._DiaDiems.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DiaDiems(DiaDiem entity)
		{
			this.SendPropertyChanging();
			entity.DanhMuc = this;
		}
		
		private void detach_DiaDiems(DiaDiem entity)
		{
			this.SendPropertyChanging();
			entity.DanhMuc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiem")]
	public partial class DiaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDiaDiem;
		
		private string _TenDiaDiem;
		
		private string _Slug;
		
		private string _MoTaNgan;
		
		private string _MoTaChiTiet;
		
		private int _MaDanhMuc;
		
		private System.Nullable<decimal> _GiaVe;
		
		private string _GioMoCua;
		
		private string _VungMien;
		
		private System.Nullable<decimal> _KinhDo;
		
		private System.Nullable<decimal> _ViDo;
		
		private string _DiaChiChiTiet;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private string _Website;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<int> _LuotXem;
		
		private System.Nullable<double> _DiemDanhGiaTB;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private EntitySet<AnhDiaDiem> _AnhDiaDiems;
		
		private EntitySet<TraiNghiem> _TraiNghiems;
		
		private EntitySet<GiaVeChiTiet> _GiaVeChiTiets;
		
		private EntityRef<DanhMuc> _DanhMuc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaDiemChanging(int value);
    partial void OnMaDiaDiemChanged();
    partial void OnTenDiaDiemChanging(string value);
    partial void OnTenDiaDiemChanged();
    partial void OnSlugChanging(string value);
    partial void OnSlugChanged();
    partial void OnMoTaNganChanging(string value);
    partial void OnMoTaNganChanged();
    partial void OnMoTaChiTietChanging(string value);
    partial void OnMoTaChiTietChanged();
    partial void OnMaDanhMucChanging(int value);
    partial void OnMaDanhMucChanged();
    partial void OnGiaVeChanging(System.Nullable<decimal> value);
    partial void OnGiaVeChanged();
    partial void OnGioMoCuaChanging(string value);
    partial void OnGioMoCuaChanged();
    partial void OnVungMienChanging(string value);
    partial void OnVungMienChanged();
    partial void OnKinhDoChanging(System.Nullable<decimal> value);
    partial void OnKinhDoChanged();
    partial void OnViDoChanging(System.Nullable<decimal> value);
    partial void OnViDoChanged();
    partial void OnDiaChiChiTietChanging(string value);
    partial void OnDiaChiChiTietChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OnDiemDanhGiaTBChanging(System.Nullable<double> value);
    partial void OnDiemDanhGiaTBChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    #endregion
		
		public DiaDiem()
		{
			this._AnhDiaDiems = new EntitySet<AnhDiaDiem>(new Action<AnhDiaDiem>(this.attach_AnhDiaDiems), new Action<AnhDiaDiem>(this.detach_AnhDiaDiems));
			this._TraiNghiems = new EntitySet<TraiNghiem>(new Action<TraiNghiem>(this.attach_TraiNghiems), new Action<TraiNghiem>(this.detach_TraiNghiems));
			this._GiaVeChiTiets = new EntitySet<GiaVeChiTiet>(new Action<GiaVeChiTiet>(this.attach_GiaVeChiTiets), new Action<GiaVeChiTiet>(this.detach_GiaVeChiTiets));
			this._DanhMuc = default(EntityRef<DanhMuc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDiaDiem", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenDiaDiem
		{
			get
			{
				return this._TenDiaDiem;
			}
			set
			{
				if ((this._TenDiaDiem != value))
				{
					this.OnTenDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._TenDiaDiem = value;
					this.SendPropertyChanged("TenDiaDiem");
					this.OnTenDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Slug", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string Slug
		{
			get
			{
				return this._Slug;
			}
			set
			{
				if ((this._Slug != value))
				{
					this.OnSlugChanging(value);
					this.SendPropertyChanging();
					this._Slug = value;
					this.SendPropertyChanged("Slug");
					this.OnSlugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaNgan", DbType="NVarChar(MAX)")]
		public string MoTaNgan
		{
			get
			{
				return this._MoTaNgan;
			}
			set
			{
				if ((this._MoTaNgan != value))
				{
					this.OnMoTaNganChanging(value);
					this.SendPropertyChanging();
					this._MoTaNgan = value;
					this.SendPropertyChanged("MoTaNgan");
					this.OnMoTaNganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTaChiTiet", DbType="NVarChar(MAX)")]
		public string MoTaChiTiet
		{
			get
			{
				return this._MoTaChiTiet;
			}
			set
			{
				if ((this._MoTaChiTiet != value))
				{
					this.OnMoTaChiTietChanging(value);
					this.SendPropertyChanging();
					this._MoTaChiTiet = value;
					this.SendPropertyChanged("MoTaChiTiet");
					this.OnMoTaChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDanhMuc", DbType="Int NOT NULL")]
		public int MaDanhMuc
		{
			get
			{
				return this._MaDanhMuc;
			}
			set
			{
				if ((this._MaDanhMuc != value))
				{
					if (this._DanhMuc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDanhMucChanging(value);
					this.SendPropertyChanging();
					this._MaDanhMuc = value;
					this.SendPropertyChanged("MaDanhMuc");
					this.OnMaDanhMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaVe", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GiaVe
		{
			get
			{
				return this._GiaVe;
			}
			set
			{
				if ((this._GiaVe != value))
				{
					this.OnGiaVeChanging(value);
					this.SendPropertyChanging();
					this._GiaVe = value;
					this.SendPropertyChanged("GiaVe");
					this.OnGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioMoCua", DbType="NVarChar(100)")]
		public string GioMoCua
		{
			get
			{
				return this._GioMoCua;
			}
			set
			{
				if ((this._GioMoCua != value))
				{
					this.OnGioMoCuaChanging(value);
					this.SendPropertyChanging();
					this._GioMoCua = value;
					this.SendPropertyChanged("GioMoCua");
					this.OnGioMoCuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VungMien", DbType="NVarChar(50)")]
		public string VungMien
		{
			get
			{
				return this._VungMien;
			}
			set
			{
				if ((this._VungMien != value))
				{
					this.OnVungMienChanging(value);
					this.SendPropertyChanging();
					this._VungMien = value;
					this.SendPropertyChanged("VungMien");
					this.OnVungMienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KinhDo", DbType="Decimal(18,10)")]
		public System.Nullable<decimal> KinhDo
		{
			get
			{
				return this._KinhDo;
			}
			set
			{
				if ((this._KinhDo != value))
				{
					this.OnKinhDoChanging(value);
					this.SendPropertyChanging();
					this._KinhDo = value;
					this.SendPropertyChanged("KinhDo");
					this.OnKinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViDo", DbType="Decimal(18,10)")]
		public System.Nullable<decimal> ViDo
		{
			get
			{
				return this._ViDo;
			}
			set
			{
				if ((this._ViDo != value))
				{
					this.OnViDoChanging(value);
					this.SendPropertyChanging();
					this._ViDo = value;
					this.SendPropertyChanged("ViDo");
					this.OnViDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChiChiTiet", DbType="NVarChar(MAX)")]
		public string DiaChiChiTiet
		{
			get
			{
				return this._DiaChiChiTiet;
			}
			set
			{
				if ((this._DiaChiChiTiet != value))
				{
					this.OnDiaChiChiTietChanging(value);
					this.SendPropertyChanging();
					this._DiaChiChiTiet = value;
					this.SendPropertyChanged("DiaChiChiTiet");
					this.OnDiaChiChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(20)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(255)")]
		public string Website
		{
			get
			{
				return this._Website;
			}
			set
			{
				if ((this._Website != value))
				{
					this.OnWebsiteChanging(value);
					this.SendPropertyChanging();
					this._Website = value;
					this.SendPropertyChanged("Website");
					this.OnWebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
		public System.Nullable<int> LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiemDanhGiaTB", DbType="Float")]
		public System.Nullable<double> DiemDanhGiaTB
		{
			get
			{
				return this._DiemDanhGiaTB;
			}
			set
			{
				if ((this._DiemDanhGiaTB != value))
				{
					this.OnDiemDanhGiaTBChanging(value);
					this.SendPropertyChanging();
					this._DiemDanhGiaTB = value;
					this.SendPropertyChanged("DiemDanhGiaTB");
					this.OnDiemDanhGiaTBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_AnhDiaDiem", Storage="_AnhDiaDiems", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem")]
		public EntitySet<AnhDiaDiem> AnhDiaDiems
		{
			get
			{
				return this._AnhDiaDiems;
			}
			set
			{
				this._AnhDiaDiems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TraiNghiem", Storage="_TraiNghiems", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem")]
		public EntitySet<TraiNghiem> TraiNghiems
		{
			get
			{
				return this._TraiNghiems;
			}
			set
			{
				this._TraiNghiems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_GiaVeChiTiet", Storage="_GiaVeChiTiets", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem")]
		public EntitySet<GiaVeChiTiet> GiaVeChiTiets
		{
			get
			{
				return this._GiaVeChiTiets;
			}
			set
			{
				this._GiaVeChiTiets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_DiaDiem", Storage="_DanhMuc", ThisKey="MaDanhMuc", OtherKey="MaDanhMuc", IsForeignKey=true)]
		public DanhMuc DanhMuc
		{
			get
			{
				return this._DanhMuc.Entity;
			}
			set
			{
				DanhMuc previousValue = this._DanhMuc.Entity;
				if (((previousValue != value) 
							|| (this._DanhMuc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DanhMuc.Entity = null;
						previousValue.DiaDiems.Remove(this);
					}
					this._DanhMuc.Entity = value;
					if ((value != null))
					{
						value.DiaDiems.Add(this);
						this._MaDanhMuc = value.MaDanhMuc;
					}
					else
					{
						this._MaDanhMuc = default(int);
					}
					this.SendPropertyChanged("DanhMuc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AnhDiaDiems(AnhDiaDiem entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_AnhDiaDiems(AnhDiaDiem entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
		
		private void attach_TraiNghiems(TraiNghiem entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_TraiNghiems(TraiNghiem entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
		
		private void attach_GiaVeChiTiets(GiaVeChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_GiaVeChiTiets(GiaVeChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GiaVeChiTiet")]
	public partial class GiaVeChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaGiaVe;
		
		private int _MaDiaDiem;
		
		private string _LoaiKhach;
		
		private decimal _Gia;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaVeChanging(int value);
    partial void OnMaGiaVeChanged();
    partial void OnMaDiaDiemChanging(int value);
    partial void OnMaDiaDiemChanged();
    partial void OnLoaiKhachChanging(string value);
    partial void OnLoaiKhachChanged();
    partial void OnGiaChanging(decimal value);
    partial void OnGiaChanged();
    #endregion
		
		public GiaVeChiTiet()
		{
			this._DiaDiem = default(EntityRef<DiaDiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaVe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaGiaVe
		{
			get
			{
				return this._MaGiaVe;
			}
			set
			{
				if ((this._MaGiaVe != value))
				{
					this.OnMaGiaVeChanging(value);
					this.SendPropertyChanging();
					this._MaGiaVe = value;
					this.SendPropertyChanged("MaGiaVe");
					this.OnMaGiaVeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="Int NOT NULL")]
		public int MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiKhach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiKhach
		{
			get
			{
				return this._LoaiKhach;
			}
			set
			{
				if ((this._LoaiKhach != value))
				{
					this.OnLoaiKhachChanging(value);
					this.SendPropertyChanging();
					this._LoaiKhach = value;
					this.SendPropertyChanged("LoaiKhach");
					this.OnLoaiKhachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Decimal(18,2) NOT NULL")]
		public decimal Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_GiaVeChiTiet", Storage="_DiaDiem", ThisKey="MaDiaDiem", OtherKey="MaDiaDiem", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.GiaVeChiTiets.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.GiaVeChiTiets.Add(this);
						this._MaDiaDiem = value.MaDiaDiem;
					}
					else
					{
						this._MaDiaDiem = default(int);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDung")]
	public partial class NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNguoiDung;
		
		private string _HoTen;
		
		private string _Email;
		
		private string _MatKhauHash;
		
		private string _SoDienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _TieuSu;
		
		private string _ThanhPho;
		
		private string _QuocGia;
		
		private string _AnhDaiDien;
		
		private int _VaiTro;
		
		private bool _TrangThai;
		
		private System.DateTime _NgayTao;
		
		private System.Nullable<System.DateTime> _NgayCapNhat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(int value);
    partial void OnMaNguoiDungChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatKhauHashChanging(string value);
    partial void OnMatKhauHashChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnTieuSuChanging(string value);
    partial void OnTieuSuChanged();
    partial void OnThanhPhoChanging(string value);
    partial void OnThanhPhoChanged();
    partial void OnQuocGiaChanging(string value);
    partial void OnQuocGiaChanged();
    partial void OnAnhDaiDienChanging(string value);
    partial void OnAnhDaiDienChanged();
    partial void OnVaiTroChanging(int value);
    partial void OnVaiTroChanged();
    partial void OnTrangThaiChanging(bool value);
    partial void OnTrangThaiChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    partial void OnNgayCapNhatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapNhatChanged();
    #endregion
		
		public NguoiDung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauHash", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string MatKhauHash
		{
			get
			{
				return this._MatKhauHash;
			}
			set
			{
				if ((this._MatKhauHash != value))
				{
					this.OnMatKhauHashChanging(value);
					this.SendPropertyChanging();
					this._MatKhauHash = value;
					this.SendPropertyChanged("MatKhauHash");
					this.OnMatKhauHashChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(20)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TieuSu", DbType="NVarChar(500)")]
		public string TieuSu
		{
			get
			{
				return this._TieuSu;
			}
			set
			{
				if ((this._TieuSu != value))
				{
					this.OnTieuSuChanging(value);
					this.SendPropertyChanging();
					this._TieuSu = value;
					this.SendPropertyChanged("TieuSu");
					this.OnTieuSuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhPho", DbType="NVarChar(100)")]
		public string ThanhPho
		{
			get
			{
				return this._ThanhPho;
			}
			set
			{
				if ((this._ThanhPho != value))
				{
					this.OnThanhPhoChanging(value);
					this.SendPropertyChanging();
					this._ThanhPho = value;
					this.SendPropertyChanged("ThanhPho");
					this.OnThanhPhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuocGia", DbType="NVarChar(100)")]
		public string QuocGia
		{
			get
			{
				return this._QuocGia;
			}
			set
			{
				if ((this._QuocGia != value))
				{
					this.OnQuocGiaChanging(value);
					this.SendPropertyChanging();
					this._QuocGia = value;
					this.SendPropertyChanged("QuocGia");
					this.OnQuocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhDaiDien", DbType="NVarChar(MAX)")]
		public string AnhDaiDien
		{
			get
			{
				return this._AnhDaiDien;
			}
			set
			{
				if ((this._AnhDaiDien != value))
				{
					this.OnAnhDaiDienChanging(value);
					this.SendPropertyChanging();
					this._AnhDaiDien = value;
					this.SendPropertyChanged("AnhDaiDien");
					this.OnAnhDaiDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VaiTro", DbType="Int NOT NULL")]
		public int VaiTro
		{
			get
			{
				return this._VaiTro;
			}
			set
			{
				if ((this._VaiTro != value))
				{
					this.OnVaiTroChanging(value);
					this.SendPropertyChanging();
					this._VaiTro = value;
					this.SendPropertyChanged("VaiTro");
					this.OnVaiTroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit NOT NULL")]
		public bool TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime2 NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCapNhat", DbType="DateTime2")]
		public System.Nullable<System.DateTime> NgayCapNhat
		{
			get
			{
				return this._NgayCapNhat;
			}
			set
			{
				if ((this._NgayCapNhat != value))
				{
					this.OnNgayCapNhatChanging(value);
					this.SendPropertyChanging();
					this._NgayCapNhat = value;
					this.SendPropertyChanged("NgayCapNhat");
					this.OnNgayCapNhatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
